criptos/coins/urls.py
from django.contrib import admin
from django.urls import path
from .views import index, wallet_add, WalletDelete, WalletList, register

urlpatterns = [
    path('', index, name='index'),
    path('wallet/',WalletList.as_view(),name='get_wallet'),
    path('wallet/<str:pk>',wallet_add,name='wallet_add'),
    path('wallet/<str:pk>/delete', WalletDelete.as_view(),name='delete_coin'),
    path('register/',register,name='register')
]

criptos/criptos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
]
urlpatterns += [
    path('coins/', include('coins.urls')),
]
urlpatterns += [
    # Redirijo el inicio de mi proyecto ('/') a catalog ('/catalog)
    path('', RedirectView.as_view(url='/coins/', permanent=True)),
]
# Autentificacion de usuarios
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

criptos/coins/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.db.models.fields import CharField, DateField
from django.db.models.fields.related import ForeignKey
from django.contrib.auth.models import User  

class Wallet(models.Model):
    crypto = CharField(primary_key=True, max_length=255)
    symbol = CharField(max_length=100, blank=False, null=False)
    price = CharField(max_length=100)
    last_updated = CharField(max_length=100,blank=True,null=True)
    image = CharField(max_length=255,blank=True,null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    class Meta :
        ordering = ["price"]

    def __str__(self):
        return self.crypto

criptos/coins/forms.py
from django import forms
from django.forms import fields
from .models import Wallet
from django.contrib.auth.models import User  

class WalletForm(forms.ModelForm):
    class Meta : 
        model = Wallet
        fields = '__all__' 

class UserForm(forms.ModelForm):
    class Meta :
        model = User
        fields = ('username', 'email', 'password')

criptos/coins/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.decorators.csrf import csrf_exempt  # Exime la vista del token
from django.views.generic import CreateView, DeleteView, ListView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.contrib.auth.models import Group
from django.contrib.auth.forms import UserCreationForm

from pycoingecko import CoinGeckoAPI
cg = CoinGeckoAPI()

from .models import Wallet
from .forms import WalletForm, UserForm

# Función vista para la página inicio del sitio.
def index(request):
    coins = cg.get_coins_list()
    page = request.GET.get("page", 1)
    # Paginacion
    paginator = Paginator(coins, 40)
    try:
        coins = paginator.page(page)
    except PageNotAnInteger:
        coins = paginator.page(1)
    except EmptyPage:
        coins = paginator.page(paginator.num_pages)
    return render(request,'index.html',{'coins':coins})


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            group = Group.objects.get(name='Users')
            user.groups.add(group)
            return redirect('login')
    else:
        form = UserCreationForm()
    return render(request,'auth/user_form.html',{'form':form})

@login_required
def wallet_add(request, pk):
    coin = cg.get_coins_markets(vs_currency='usd',ids=pk)
    data = {'price':coin[0]['current_price'], 'symbol':coin[0]['symbol'],'crypto':pk,'image':coin[0]['image'],'last_updated':coin[0]['last_updated'],'user':request.user}
    form = WalletForm(data)
    if form.is_valid(): 
        form.save()
    return redirect('get_wallet')

"""
--Vista de funcion--
def get_wallet(request):
    wallet = Wallet.objects.all()
    context = {'wallet':wallet}
    return render(request,'wallet/wallet.html',context)
"""

class WalletList(LoginRequiredMixin, ListView):
    model = Wallet

"""
--Vista de funcion--
def delete_coin(request, pk):
    coin = Wallet.objects.get(crypto = pk)
    coin.delete()
    return redirect('get_wallet')

"""
class WalletDelete(LoginRequiredMixin,DeleteView):
    model = Wallet
    success_url = reverse_lazy('get_wallet')

criptos/coins/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <title>CoinsApp</title>
    {% endblock title %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-2">
                {% block sidebar %}
                <ul class="sidebar-nav">
                    <li><a href="{% url 'index' %}">Home</a></li>
                    <br>
                    {% if user.is_authenticated %}
                    <li>User: {{ user.get_username }}</li>
                    <li><a href="{% url 'get_wallet' %}">My Wallet</a></li>
                    <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
                    {% else %}
                    <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
                    <li><a href="{% url 'register'%}">Register</a></li>
                    {% endif %}

                </ul>
                {% endblock %}
            </div>
            <div class="col-sm-10 ">
                {% block content %}{% endblock %}

                <!-- Paginacion -->
                {% block pagination %}
                {% if coins.has_other_pages %}
                <nav aria-label="Score pagination" class="mb-4">
                    <ul class="pagination">
                        {% if coins.has_previous%}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ coins.previous_page_number }}"> Página anterior </a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <span class="page-link"> Página anterior </span>
                        </li>
                        {% endif %}

                        {% if coins.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ coins.next_page_number }}"> Página siguiente </a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <span class="page-link"> Página siguiente </span>
                        </li>
                        {% endif %}
                    </ul>
                </nav>
                {% endif %}
                {% endblock %}

            </div>
        </div>

    </div>
</body>

</html>

criptos/coins/templates/coins/wallet_add.html
{% extends "base_generic.html" %}

{% block title %} <title>Coin</title> {% endblock %}

{% block content %}
<form method="post" action="">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Guardar</button>
</form>
{% endblock %}

criptos/coins/templates/coins/wallet_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Coin</h1>

<p>Are you sure you want to delete the coin: {{ wallet }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

criptos/coins/templates/coins/wallet_list.html
{% extends "base_generic.html" %}

{% block title %} <title>Wallet</title> {% endblock %}

{% block content %}
    <h2>Your Coins!</h2>
    <table border="2">
        <thead>
            <tr>
                <th>Crypto</th>
                <th>Symbol</th>
                <th>Price</th>
                <th>Last Updated</th>
                <th>Image</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for coin in user.wallet_set.all %}
            <tr>
                <th>{{coin.crypto}}</th>
                <th>{{coin.symbol}}</th>
                <th>{{coin.price}}</th>
                <th>{{coin.last_updated}}</th>
                <th><img src="{{coin.image}}" alt="{{coin.crypto}}" ></th>
                <th><a href="{% url 'delete_coin' coin.crypto %}">Delete</a></th>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

criptos/coins/templates/index.html
{% extends "base_generic.html" %}

{% block title %} 
    <title>Cryptos</title>
{% endblock %}
{% block content %}
    <h1>CoinsApp Home</h1>
    <h2>Coins</h2>
    <table border="3">
        <thead>
            <tr>
                <th>Id</th>
                <th>Symbol</th>
                <th>Name</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for coin in coins %}
            <tr>
                <th>{{coin.id}}</th>
                <th>{{coin.symbol}}</th>
                <th>{{coin.name}}</th>
                <th><a href="{% url 'wallet_add' coin.id %}">Add to Wallet</a></th>
            </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock content %}